{% set name = "pytest_parallel_mpi" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onera/pytest_parallel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42074d1ee4c24eb5c2bc448278ff44c5125d5f9b4ceac27f4411efb91c14a97e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pytest >=6.2.5
    - python >={{ python_min }}
    - mpi4py
    - numpy

test:
  imports:
    - pytest_parallel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/onera/pytest_parallel
  summary: a pytest plugin to manage test in distributed way with MPI Standard
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MicK7
