{% set name = "pytest_parallel_mpi" %}
{% set version = "1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onera/pytest_parallel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e467cb113916d67324adfacadeb95cc95ab694d5c004d806f4c7912039642dbf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pytest >=6.2.5
    - python >=3.8
    - mpi4py
    - numpy

test:
  imports:
    - pytest_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onera/pytest_parallel
  summary: a pytest plugin to manage test in distributed way with MPI Standard
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MicK7
